name: Build & Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config.js from secrets
        run: |
          mkdir -p assets
          cat > assets/config.js << 'EOF'
          // generado por GitHub Actions
          window.__CONF__ = {
            SUPABASE_URL: "${{ secrets.PUBLIC_SUPABASE_URL }}",
            SUPABASE_ANON_KEY: "${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}"
          };
          EOF

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
