name: Clean Supabase Institutions

on:
  workflow_dispatch:     # permite dispararlo manualmente desde GitHub
  schedule:
    - cron: '0 3 * * 0'  # opcional: cada domingo a las 03:00 UTC (ajusta)

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm ci || (npm i)

      - name: Run cleaning script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          node clean_institutions.js
