name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Genera assets/config.js con secrets del repo
      - name: Create config.js from secrets
        run: |
          mkdir -p assets
          cat > assets/config.js << 'EOF'
          window.__CONF__ = {
            SUPABASE_URL: "${{ secrets.SUPABASE_URL }}",
            SUPABASE_ANON_KEY: "${{ secrets.SUPABASE_ANON_KEY }}",
            TABLES: {
              tabla1: "instituciones",
              tabla2: "cultura_patromonio_repositorios",
              tabla3: "infraestructura_deportiva",
              tabla4: "universidades_tecnicos"
            }
          };
          EOF
          echo "config.js generated"

      # Si tu sitio requiere build, ponlo aquí (npm ci && npm run build).
      # Para sitio estático, sólo empaquetamos la raíz.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    # Despliega sólo en push a main (no en PR)
    if: github.event_name != 'pull_request'
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
